// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/common.proto

package common

import (
	context "context"
	fmt "fmt"
	common "github.com/becosuke/tasks-api/protogen/message/common"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("service/common.proto", fileDescriptor_dfd83b45a0f36f9d) }

var fileDescriptor_dfd83b45a0f36f9d = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x83, 0x8a, 0xea, 0x41, 0x44, 0xa5, 0x64, 0xd2, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5,
	0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x8a, 0x21,
	0xaa, 0xa5, 0x44, 0x72, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x51, 0xcd, 0x30, 0x4a, 0xe1, 0x62, 0x73,
	0x06, 0xf3, 0x85, 0xa2, 0xb8, 0x58, 0x02, 0x32, 0xf3, 0xd2, 0x85, 0xa4, 0xf5, 0xa0, 0x0a, 0xa1,
	0xc6, 0xea, 0x81, 0x44, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0xa4, 0x64, 0xb0, 0x4b, 0x16,
	0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x2a, 0x89, 0x37, 0x5d, 0x7e, 0x32, 0x99, 0x49, 0x50, 0x88, 0x5f,
	0xbf, 0xcc, 0x10, 0x6a, 0x8d, 0x7e, 0x41, 0x66, 0x5e, 0xba, 0x93, 0x79, 0x94, 0x69, 0x7a, 0x66,
	0x49, 0x46, 0x69, 0x12, 0x48, 0x9b, 0x7e, 0x52, 0x6a, 0x72, 0x7e, 0x71, 0x69, 0x76, 0xaa, 0x7e,
	0x49, 0x62, 0x71, 0x76, 0xb1, 0x2e, 0xc8, 0xb9, 0x60, 0xc7, 0xa4, 0xa7, 0xe6, 0xe9, 0xa3, 0x7a,
	0x34, 0x89, 0x0d, 0x2c, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x79, 0x33, 0x9e, 0x35, 0x01,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommonClient is the client API for Common service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommonClient interface {
	Ping(ctx context.Context, in *common.PingRequest, opts ...grpc.CallOption) (*common.PingResponse, error)
}

type commonClient struct {
	cc *grpc.ClientConn
}

func NewCommonClient(cc *grpc.ClientConn) CommonClient {
	return &commonClient{cc}
}

func (c *commonClient) Ping(ctx context.Context, in *common.PingRequest, opts ...grpc.CallOption) (*common.PingResponse, error) {
	out := new(common.PingResponse)
	err := c.cc.Invoke(ctx, "/service.common.Common/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonServer is the server API for Common service.
type CommonServer interface {
	Ping(context.Context, *common.PingRequest) (*common.PingResponse, error)
}

// UnimplementedCommonServer can be embedded to have forward compatible implementations.
type UnimplementedCommonServer struct {
}

func (*UnimplementedCommonServer) Ping(ctx context.Context, req *common.PingRequest) (*common.PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterCommonServer(s *grpc.Server, srv CommonServer) {
	s.RegisterService(&_Common_serviceDesc, srv)
}

func _Common_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.common.Common/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServer).Ping(ctx, req.(*common.PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Common_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.common.Common",
	HandlerType: (*CommonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Common_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/common.proto",
}
