// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/list.proto

package list // import "github.com/becosuke/tasks-api/protogen/service/list"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import list "github.com/becosuke/tasks-api/protogen/message/list"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_79c42a1592ce2777, []int{0}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CreateResponse struct {
	Document             *list.Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_79c42a1592ce2777, []int{1}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(dst, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetDocument() *list.Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type UpdateRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_79c42a1592ce2777, []int{2}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type UpdateResponse struct {
	Document             *list.Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_79c42a1592ce2777, []int{3}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(dst, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetDocument() *list.Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type DeleteRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_79c42a1592ce2777, []int{4}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponse struct {
	Document             *list.Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_79c42a1592ce2777, []int{5}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(dst, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetDocument() *list.Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type GetDocumentRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentRequest) Reset()         { *m = GetDocumentRequest{} }
func (m *GetDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentRequest) ProtoMessage()    {}
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_79c42a1592ce2777, []int{6}
}
func (m *GetDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentRequest.Unmarshal(m, b)
}
func (m *GetDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentRequest.Marshal(b, m, deterministic)
}
func (dst *GetDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentRequest.Merge(dst, src)
}
func (m *GetDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentRequest.Size(m)
}
func (m *GetDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentRequest proto.InternalMessageInfo

func (m *GetDocumentRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetDocumentResponse struct {
	Document             *list.Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetDocumentResponse) Reset()         { *m = GetDocumentResponse{} }
func (m *GetDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*GetDocumentResponse) ProtoMessage()    {}
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_79c42a1592ce2777, []int{7}
}
func (m *GetDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentResponse.Unmarshal(m, b)
}
func (m *GetDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentResponse.Marshal(b, m, deterministic)
}
func (dst *GetDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentResponse.Merge(dst, src)
}
func (m *GetDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_GetDocumentResponse.Size(m)
}
func (m *GetDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentResponse proto.InternalMessageInfo

func (m *GetDocumentResponse) GetDocument() *list.Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type GetDocumentsRequest struct {
	Ids                  []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentsRequest) Reset()         { *m = GetDocumentsRequest{} }
func (m *GetDocumentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsRequest) ProtoMessage()    {}
func (*GetDocumentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_79c42a1592ce2777, []int{8}
}
func (m *GetDocumentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsRequest.Unmarshal(m, b)
}
func (m *GetDocumentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsRequest.Marshal(b, m, deterministic)
}
func (dst *GetDocumentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsRequest.Merge(dst, src)
}
func (m *GetDocumentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsRequest.Size(m)
}
func (m *GetDocumentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsRequest proto.InternalMessageInfo

func (m *GetDocumentsRequest) GetIds() []uint64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetDocumentsResponse struct {
	Documents            []*list.Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetDocumentsResponse) Reset()         { *m = GetDocumentsResponse{} }
func (m *GetDocumentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsResponse) ProtoMessage()    {}
func (*GetDocumentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_79c42a1592ce2777, []int{9}
}
func (m *GetDocumentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsResponse.Unmarshal(m, b)
}
func (m *GetDocumentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsResponse.Marshal(b, m, deterministic)
}
func (dst *GetDocumentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsResponse.Merge(dst, src)
}
func (m *GetDocumentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsResponse.Size(m)
}
func (m *GetDocumentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsResponse proto.InternalMessageInfo

func (m *GetDocumentsResponse) GetDocuments() []*list.Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type GetDocumentsAllRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentsAllRequest) Reset()         { *m = GetDocumentsAllRequest{} }
func (m *GetDocumentsAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsAllRequest) ProtoMessage()    {}
func (*GetDocumentsAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_79c42a1592ce2777, []int{10}
}
func (m *GetDocumentsAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsAllRequest.Unmarshal(m, b)
}
func (m *GetDocumentsAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsAllRequest.Marshal(b, m, deterministic)
}
func (dst *GetDocumentsAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsAllRequest.Merge(dst, src)
}
func (m *GetDocumentsAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsAllRequest.Size(m)
}
func (m *GetDocumentsAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsAllRequest proto.InternalMessageInfo

func (m *GetDocumentsAllRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetDocumentsAllRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetDocumentsAllResponse struct {
	Documents            []*list.Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetDocumentsAllResponse) Reset()         { *m = GetDocumentsAllResponse{} }
func (m *GetDocumentsAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsAllResponse) ProtoMessage()    {}
func (*GetDocumentsAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_79c42a1592ce2777, []int{11}
}
func (m *GetDocumentsAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsAllResponse.Unmarshal(m, b)
}
func (m *GetDocumentsAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsAllResponse.Marshal(b, m, deterministic)
}
func (dst *GetDocumentsAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsAllResponse.Merge(dst, src)
}
func (m *GetDocumentsAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsAllResponse.Size(m)
}
func (m *GetDocumentsAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsAllResponse proto.InternalMessageInfo

func (m *GetDocumentsAllResponse) GetDocuments() []*list.Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type GetCountAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCountAllRequest) Reset()         { *m = GetCountAllRequest{} }
func (m *GetCountAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetCountAllRequest) ProtoMessage()    {}
func (*GetCountAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_79c42a1592ce2777, []int{12}
}
func (m *GetCountAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountAllRequest.Unmarshal(m, b)
}
func (m *GetCountAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountAllRequest.Marshal(b, m, deterministic)
}
func (dst *GetCountAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountAllRequest.Merge(dst, src)
}
func (m *GetCountAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetCountAllRequest.Size(m)
}
func (m *GetCountAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountAllRequest proto.InternalMessageInfo

type GetCountAllResponse struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCountAllResponse) Reset()         { *m = GetCountAllResponse{} }
func (m *GetCountAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetCountAllResponse) ProtoMessage()    {}
func (*GetCountAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_79c42a1592ce2777, []int{13}
}
func (m *GetCountAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountAllResponse.Unmarshal(m, b)
}
func (m *GetCountAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountAllResponse.Marshal(b, m, deterministic)
}
func (dst *GetCountAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountAllResponse.Merge(dst, src)
}
func (m *GetCountAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetCountAllResponse.Size(m)
}
func (m *GetCountAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountAllResponse proto.InternalMessageInfo

func (m *GetCountAllResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "service.list.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "service.list.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "service.list.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "service.list.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "service.list.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "service.list.DeleteResponse")
	proto.RegisterType((*GetDocumentRequest)(nil), "service.list.GetDocumentRequest")
	proto.RegisterType((*GetDocumentResponse)(nil), "service.list.GetDocumentResponse")
	proto.RegisterType((*GetDocumentsRequest)(nil), "service.list.GetDocumentsRequest")
	proto.RegisterType((*GetDocumentsResponse)(nil), "service.list.GetDocumentsResponse")
	proto.RegisterType((*GetDocumentsAllRequest)(nil), "service.list.GetDocumentsAllRequest")
	proto.RegisterType((*GetDocumentsAllResponse)(nil), "service.list.GetDocumentsAllResponse")
	proto.RegisterType((*GetCountAllRequest)(nil), "service.list.GetCountAllRequest")
	proto.RegisterType((*GetCountAllResponse)(nil), "service.list.GetCountAllResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ListClient is the client API for List service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ListClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	GetDocuments(ctx context.Context, in *GetDocumentsRequest, opts ...grpc.CallOption) (*GetDocumentsResponse, error)
	GetDocumentsAll(ctx context.Context, in *GetDocumentsAllRequest, opts ...grpc.CallOption) (*GetDocumentsAllResponse, error)
	GetCountAll(ctx context.Context, in *GetCountAllRequest, opts ...grpc.CallOption) (*GetCountAllResponse, error)
}

type listClient struct {
	cc *grpc.ClientConn
}

func NewListClient(cc *grpc.ClientConn) ListClient {
	return &listClient{cc}
}

func (c *listClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/service.list.List/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/service.list.List/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/service.list.List/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, "/service.list.List/GetDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listClient) GetDocuments(ctx context.Context, in *GetDocumentsRequest, opts ...grpc.CallOption) (*GetDocumentsResponse, error) {
	out := new(GetDocumentsResponse)
	err := c.cc.Invoke(ctx, "/service.list.List/GetDocuments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listClient) GetDocumentsAll(ctx context.Context, in *GetDocumentsAllRequest, opts ...grpc.CallOption) (*GetDocumentsAllResponse, error) {
	out := new(GetDocumentsAllResponse)
	err := c.cc.Invoke(ctx, "/service.list.List/GetDocumentsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listClient) GetCountAll(ctx context.Context, in *GetCountAllRequest, opts ...grpc.CallOption) (*GetCountAllResponse, error) {
	out := new(GetCountAllResponse)
	err := c.cc.Invoke(ctx, "/service.list.List/GetCountAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListServer is the server API for List service.
type ListServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	GetDocuments(context.Context, *GetDocumentsRequest) (*GetDocumentsResponse, error)
	GetDocumentsAll(context.Context, *GetDocumentsAllRequest) (*GetDocumentsAllResponse, error)
	GetCountAll(context.Context, *GetCountAllRequest) (*GetCountAllResponse, error)
}

func RegisterListServer(s *grpc.Server, srv ListServer) {
	s.RegisterService(&_List_serviceDesc, srv)
}

func _List_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.list.List/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _List_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.list.List/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _List_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.list.List/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _List_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.list.List/GetDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _List_GetDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServer).GetDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.list.List/GetDocuments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServer).GetDocuments(ctx, req.(*GetDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _List_GetDocumentsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentsAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServer).GetDocumentsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.list.List/GetDocumentsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServer).GetDocumentsAll(ctx, req.(*GetDocumentsAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _List_GetCountAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCountAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServer).GetCountAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.list.List/GetCountAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServer).GetCountAll(ctx, req.(*GetCountAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _List_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.list.List",
	HandlerType: (*ListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _List_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _List_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _List_Delete_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _List_GetDocument_Handler,
		},
		{
			MethodName: "GetDocuments",
			Handler:    _List_GetDocuments_Handler,
		},
		{
			MethodName: "GetDocumentsAll",
			Handler:    _List_GetDocumentsAll_Handler,
		},
		{
			MethodName: "GetCountAll",
			Handler:    _List_GetCountAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/list.proto",
}

func init() { proto.RegisterFile("service/list.proto", fileDescriptor_list_79c42a1592ce2777) }

var fileDescriptor_list_79c42a1592ce2777 = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xd1, 0x6a, 0xdb, 0x30,
	0x14, 0x86, 0x49, 0xda, 0x84, 0xf6, 0xb4, 0x69, 0xc7, 0x49, 0x9a, 0x05, 0xb7, 0xb0, 0x4c, 0xb4,
	0xac, 0x74, 0xcc, 0x62, 0xe9, 0x7a, 0xb3, 0xbb, 0xad, 0x61, 0x63, 0x50, 0x18, 0x18, 0x06, 0xa3,
	0xb0, 0x0b, 0x27, 0x56, 0x33, 0x51, 0xc7, 0xca, 0x22, 0xb9, 0xbb, 0x18, 0xbd, 0xd9, 0x2b, 0xec,
	0xd1, 0xf6, 0x0a, 0x83, 0xbd, 0xc6, 0xb0, 0x64, 0x35, 0x96, 0x1b, 0x77, 0x17, 0xb9, 0xb3, 0x8e,
	0x7e, 0xfd, 0x9f, 0x2c, 0xfd, 0x07, 0x01, 0x4a, 0x36, 0xbf, 0xe1, 0x63, 0x46, 0x63, 0x2e, 0x95,
	0x3f, 0x9b, 0x0b, 0x25, 0x70, 0x3b, 0xaf, 0xf9, 0x59, 0xcd, 0x3b, 0x98, 0x08, 0x31, 0x89, 0x19,
	0x0d, 0x67, 0x9c, 0x86, 0x49, 0x22, 0x54, 0xa8, 0xb8, 0x48, 0xa4, 0xd1, 0x7a, 0x38, 0x65, 0x52,
	0x86, 0x93, 0xe2, 0x7a, 0x72, 0x04, 0xad, 0xf3, 0x39, 0x0b, 0x15, 0x0b, 0xd8, 0xb7, 0x94, 0x49,
	0x85, 0x1d, 0x68, 0x28, 0xae, 0x62, 0xd6, 0xab, 0xf5, 0x6b, 0xc7, 0x9b, 0x81, 0x19, 0x90, 0x21,
	0xec, 0x58, 0x99, 0x9c, 0x89, 0x44, 0x32, 0x1c, 0xc0, 0x46, 0x24, 0xc6, 0xe9, 0x94, 0x25, 0x4a,
	0x4b, 0xb7, 0x06, 0x5d, 0x3f, 0xf7, 0xd7, 0x7b, 0xf1, 0x87, 0xf9, 0x6c, 0x70, 0xa7, 0x23, 0x67,
	0xd0, 0xfa, 0x34, 0x8b, 0x0a, 0xb0, 0x1d, 0xa8, 0xf3, 0x48, 0x2f, 0x5f, 0x0f, 0xea, 0x3c, 0x5a,
	0xc0, 0xeb, 0x25, 0xb8, 0x5d, 0xb6, 0x02, 0xfc, 0x09, 0xb4, 0x86, 0x2c, 0x66, 0x95, 0xf0, 0x0c,
	0x63, 0x05, 0x2b, 0x60, 0x0e, 0x01, 0xdf, 0x33, 0x75, 0x37, 0x51, 0xc1, 0xfa, 0x00, 0x6d, 0x47,
	0xb5, 0x02, 0xf0, 0x99, 0x63, 0x25, 0x2d, 0xf1, 0x11, 0xac, 0xf1, 0x48, 0xf6, 0x6a, 0xfd, 0xb5,
	0xe3, 0xf5, 0x20, 0xfb, 0x24, 0x17, 0xd0, 0x71, 0x85, 0x39, 0xf4, 0x15, 0x6c, 0x5a, 0x33, 0xa3,
	0xaf, 0xa6, 0x2e, 0x84, 0xe4, 0x1d, 0x74, 0x8b, 0x6e, 0x6f, 0xe2, 0xb8, 0x90, 0xa0, 0x98, 0x4f,
	0xb9, 0xf9, 0x83, 0x46, 0x60, 0x06, 0xd8, 0x85, 0xa6, 0xb8, 0xba, 0x92, 0x4c, 0xe9, 0xbb, 0x6d,
	0x04, 0xf9, 0x88, 0x7c, 0x84, 0xc7, 0xf7, 0x7c, 0x56, 0xda, 0x58, 0x47, 0x5f, 0xc0, 0xb9, 0x48,
	0x13, 0xb5, 0xd8, 0x14, 0x79, 0xae, 0x4f, 0x69, 0x51, 0xcd, 0x11, 0x1d, 0x68, 0x8c, 0xb3, 0x5a,
	0x7e, 0x35, 0x66, 0x30, 0xf8, 0xdb, 0x80, 0xf5, 0x0b, 0x2e, 0x15, 0x7e, 0x86, 0xa6, 0x89, 0x3d,
	0xee, 0xfb, 0xc5, 0x46, 0xf3, 0x9d, 0x9e, 0xf1, 0x0e, 0x96, 0x4f, 0x1a, 0x06, 0x69, 0xff, 0xfc,
	0xfd, 0xe7, 0x57, 0xbd, 0x45, 0x36, 0xe8, 0xcd, 0x4b, 0xdd, 0x7a, 0xaf, 0x6b, 0x27, 0xf8, 0x05,
	0x9a, 0x26, 0xd3, 0x65, 0x67, 0xa7, 0x41, 0xca, 0xce, 0x6e, 0x1b, 0x90, 0x9e, 0x76, 0x46, 0xaf,
	0x65, 0x9d, 0xe9, 0x0f, 0x1e, 0xdd, 0x66, 0xf6, 0x97, 0xd0, 0x34, 0x59, 0x2e, 0xdb, 0x3b, 0x2d,
	0x50, 0xb6, 0x77, 0xe3, 0x4f, 0xf6, 0xb4, 0xfd, 0xee, 0x89, 0x6b, 0x8f, 0x1c, 0xb6, 0x0a, 0x37,
	0x86, 0x7d, 0xd7, 0xe3, 0x7e, 0xf8, 0xbd, 0xa7, 0x0f, 0x28, 0x5c, 0x14, 0x96, 0x50, 0xdf, 0x61,
	0xbb, 0x18, 0x0e, 0xac, 0x76, 0xb2, 0xb9, 0xf7, 0xc8, 0x43, 0x92, 0x9c, 0xd6, 0xd7, 0x34, 0x0f,
	0x7b, 0x96, 0x26, 0xa9, 0xcd, 0x4f, 0xc6, 0x95, 0xb7, 0x98, 0xc2, 0x6e, 0x29, 0x95, 0x78, 0x58,
	0x6d, 0xbc, 0xc8, 0x99, 0x77, 0xf4, 0x1f, 0x55, 0xd5, 0xff, 0x4a, 0x1a, 0xc6, 0x31, 0x0a, 0x7d,
	0xb4, 0x36, 0xa5, 0x4b, 0x8e, 0xb6, 0x14, 0xeb, 0x25, 0x47, 0x5b, 0x8e, 0x38, 0xd9, 0xd7, 0xa8,
	0x3d, 0x6c, 0x3b, 0x28, 0xaa, 0x93, 0xfe, 0xf6, 0xec, 0xf2, 0x74, 0xc2, 0xd5, 0xd7, 0x74, 0xe4,
	0x8f, 0xc5, 0x94, 0x8e, 0xd8, 0x58, 0xc8, 0xf4, 0x9a, 0x51, 0x15, 0xca, 0x6b, 0xf9, 0x22, 0x7b,
	0x45, 0xf4, 0x2b, 0x31, 0x61, 0x09, 0x2d, 0xbe, 0x3d, 0xa3, 0xa6, 0x2e, 0x9f, 0xfe, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0xa3, 0x7d, 0xe3, 0x78, 0x92, 0x06, 0x00, 0x00,
}
