// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/task.proto

package task

import (
	fmt "fmt"
	common "github.com/becosuke/tasks-api/protogen/message/common"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Document struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ListId               uint64   `protobuf:"varint,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Completed            bool     `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	Enabled              bool     `protobuf:"varint,8001,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt            int64    `protobuf:"varint,8002,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8003,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,8004,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{0}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Document) GetListId() uint64 {
	if m != nil {
		return m.ListId
	}
	return 0
}

func (m *Document) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Document) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *Document) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Document) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Document) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Document) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type CreateRequest struct {
	ListId               uint64   `protobuf:"varint,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetListId() uint64 {
	if m != nil {
		return m.ListId
	}
	return 0
}

func (m *CreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CreateResponse struct {
	Result               bool      `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Document             *Document `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *CreateResponse) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type UpdateRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{3}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type UpdateResponse struct {
	Result               bool      `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Document             *Document `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{4}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *UpdateResponse) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type DeleteRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{5}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponse struct {
	Result               bool      `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Document             *Document `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{6}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *DeleteResponse) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type GetDocumentRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentRequest) Reset()         { *m = GetDocumentRequest{} }
func (m *GetDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentRequest) ProtoMessage()    {}
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{7}
}

func (m *GetDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentRequest.Unmarshal(m, b)
}
func (m *GetDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentRequest.Marshal(b, m, deterministic)
}
func (m *GetDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentRequest.Merge(m, src)
}
func (m *GetDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentRequest.Size(m)
}
func (m *GetDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentRequest proto.InternalMessageInfo

func (m *GetDocumentRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetDocumentResponse struct {
	Document             *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetDocumentResponse) Reset()         { *m = GetDocumentResponse{} }
func (m *GetDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*GetDocumentResponse) ProtoMessage()    {}
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{8}
}

func (m *GetDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentResponse.Unmarshal(m, b)
}
func (m *GetDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentResponse.Marshal(b, m, deterministic)
}
func (m *GetDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentResponse.Merge(m, src)
}
func (m *GetDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_GetDocumentResponse.Size(m)
}
func (m *GetDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentResponse proto.InternalMessageInfo

func (m *GetDocumentResponse) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type GetDocumentsRequest struct {
	Ids                  []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentsRequest) Reset()         { *m = GetDocumentsRequest{} }
func (m *GetDocumentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsRequest) ProtoMessage()    {}
func (*GetDocumentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{9}
}

func (m *GetDocumentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsRequest.Unmarshal(m, b)
}
func (m *GetDocumentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsRequest.Marshal(b, m, deterministic)
}
func (m *GetDocumentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsRequest.Merge(m, src)
}
func (m *GetDocumentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsRequest.Size(m)
}
func (m *GetDocumentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsRequest proto.InternalMessageInfo

func (m *GetDocumentsRequest) GetIds() []uint64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetDocumentsResponse struct {
	Documents            []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetDocumentsResponse) Reset()         { *m = GetDocumentsResponse{} }
func (m *GetDocumentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsResponse) ProtoMessage()    {}
func (*GetDocumentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{10}
}

func (m *GetDocumentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsResponse.Unmarshal(m, b)
}
func (m *GetDocumentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsResponse.Marshal(b, m, deterministic)
}
func (m *GetDocumentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsResponse.Merge(m, src)
}
func (m *GetDocumentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsResponse.Size(m)
}
func (m *GetDocumentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsResponse proto.InternalMessageInfo

func (m *GetDocumentsResponse) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type GetDocumentsAllRequest struct {
	Limit                uint32   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentsAllRequest) Reset()         { *m = GetDocumentsAllRequest{} }
func (m *GetDocumentsAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsAllRequest) ProtoMessage()    {}
func (*GetDocumentsAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{11}
}

func (m *GetDocumentsAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsAllRequest.Unmarshal(m, b)
}
func (m *GetDocumentsAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsAllRequest.Marshal(b, m, deterministic)
}
func (m *GetDocumentsAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsAllRequest.Merge(m, src)
}
func (m *GetDocumentsAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsAllRequest.Size(m)
}
func (m *GetDocumentsAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsAllRequest proto.InternalMessageInfo

func (m *GetDocumentsAllRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetDocumentsAllRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetDocumentsAllResponse struct {
	Documents            []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetDocumentsAllResponse) Reset()         { *m = GetDocumentsAllResponse{} }
func (m *GetDocumentsAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsAllResponse) ProtoMessage()    {}
func (*GetDocumentsAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{12}
}

func (m *GetDocumentsAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsAllResponse.Unmarshal(m, b)
}
func (m *GetDocumentsAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsAllResponse.Marshal(b, m, deterministic)
}
func (m *GetDocumentsAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsAllResponse.Merge(m, src)
}
func (m *GetDocumentsAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsAllResponse.Size(m)
}
func (m *GetDocumentsAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsAllResponse proto.InternalMessageInfo

func (m *GetDocumentsAllResponse) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type GetCountAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCountAllRequest) Reset()         { *m = GetCountAllRequest{} }
func (m *GetCountAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetCountAllRequest) ProtoMessage()    {}
func (*GetCountAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{13}
}

func (m *GetCountAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountAllRequest.Unmarshal(m, b)
}
func (m *GetCountAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountAllRequest.Marshal(b, m, deterministic)
}
func (m *GetCountAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountAllRequest.Merge(m, src)
}
func (m *GetCountAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetCountAllRequest.Size(m)
}
func (m *GetCountAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountAllRequest proto.InternalMessageInfo

type GetCountAllResponse struct {
	Count                *common.Count `protobuf:"bytes,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetCountAllResponse) Reset()         { *m = GetCountAllResponse{} }
func (m *GetCountAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetCountAllResponse) ProtoMessage()    {}
func (*GetCountAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{14}
}

func (m *GetCountAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountAllResponse.Unmarshal(m, b)
}
func (m *GetCountAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountAllResponse.Marshal(b, m, deterministic)
}
func (m *GetCountAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountAllResponse.Merge(m, src)
}
func (m *GetCountAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetCountAllResponse.Size(m)
}
func (m *GetCountAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountAllResponse proto.InternalMessageInfo

func (m *GetCountAllResponse) GetCount() *common.Count {
	if m != nil {
		return m.Count
	}
	return nil
}

type GetDocumentsByListRequest struct {
	ListId               uint64   `protobuf:"varint,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentsByListRequest) Reset()         { *m = GetDocumentsByListRequest{} }
func (m *GetDocumentsByListRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsByListRequest) ProtoMessage()    {}
func (*GetDocumentsByListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{15}
}

func (m *GetDocumentsByListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsByListRequest.Unmarshal(m, b)
}
func (m *GetDocumentsByListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsByListRequest.Marshal(b, m, deterministic)
}
func (m *GetDocumentsByListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsByListRequest.Merge(m, src)
}
func (m *GetDocumentsByListRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsByListRequest.Size(m)
}
func (m *GetDocumentsByListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsByListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsByListRequest proto.InternalMessageInfo

func (m *GetDocumentsByListRequest) GetListId() uint64 {
	if m != nil {
		return m.ListId
	}
	return 0
}

func (m *GetDocumentsByListRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetDocumentsByListRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetDocumentsByListResponse struct {
	Documents            []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetDocumentsByListResponse) Reset()         { *m = GetDocumentsByListResponse{} }
func (m *GetDocumentsByListResponse) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsByListResponse) ProtoMessage()    {}
func (*GetDocumentsByListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{16}
}

func (m *GetDocumentsByListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsByListResponse.Unmarshal(m, b)
}
func (m *GetDocumentsByListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsByListResponse.Marshal(b, m, deterministic)
}
func (m *GetDocumentsByListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsByListResponse.Merge(m, src)
}
func (m *GetDocumentsByListResponse) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsByListResponse.Size(m)
}
func (m *GetDocumentsByListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsByListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsByListResponse proto.InternalMessageInfo

func (m *GetDocumentsByListResponse) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type GetCountByListRequest struct {
	ListId               uint64   `protobuf:"varint,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCountByListRequest) Reset()         { *m = GetCountByListRequest{} }
func (m *GetCountByListRequest) String() string { return proto.CompactTextString(m) }
func (*GetCountByListRequest) ProtoMessage()    {}
func (*GetCountByListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{17}
}

func (m *GetCountByListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountByListRequest.Unmarshal(m, b)
}
func (m *GetCountByListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountByListRequest.Marshal(b, m, deterministic)
}
func (m *GetCountByListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountByListRequest.Merge(m, src)
}
func (m *GetCountByListRequest) XXX_Size() int {
	return xxx_messageInfo_GetCountByListRequest.Size(m)
}
func (m *GetCountByListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountByListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountByListRequest proto.InternalMessageInfo

func (m *GetCountByListRequest) GetListId() uint64 {
	if m != nil {
		return m.ListId
	}
	return 0
}

type GetCountByListResponse struct {
	Count                *common.Count `protobuf:"bytes,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetCountByListResponse) Reset()         { *m = GetCountByListResponse{} }
func (m *GetCountByListResponse) String() string { return proto.CompactTextString(m) }
func (*GetCountByListResponse) ProtoMessage()    {}
func (*GetCountByListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{18}
}

func (m *GetCountByListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountByListResponse.Unmarshal(m, b)
}
func (m *GetCountByListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountByListResponse.Marshal(b, m, deterministic)
}
func (m *GetCountByListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountByListResponse.Merge(m, src)
}
func (m *GetCountByListResponse) XXX_Size() int {
	return xxx_messageInfo_GetCountByListResponse.Size(m)
}
func (m *GetCountByListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountByListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountByListResponse proto.InternalMessageInfo

func (m *GetCountByListResponse) GetCount() *common.Count {
	if m != nil {
		return m.Count
	}
	return nil
}

type GetDocumentsByListAndContextsRequest struct {
	ListId               uint64   `protobuf:"varint,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	ContextIds           []uint64 `protobuf:"varint,2,rep,packed,name=context_ids,json=contextIds,proto3" json:"context_ids,omitempty"`
	Limit                uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentsByListAndContextsRequest) Reset()         { *m = GetDocumentsByListAndContextsRequest{} }
func (m *GetDocumentsByListAndContextsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsByListAndContextsRequest) ProtoMessage()    {}
func (*GetDocumentsByListAndContextsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{19}
}

func (m *GetDocumentsByListAndContextsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsByListAndContextsRequest.Unmarshal(m, b)
}
func (m *GetDocumentsByListAndContextsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsByListAndContextsRequest.Marshal(b, m, deterministic)
}
func (m *GetDocumentsByListAndContextsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsByListAndContextsRequest.Merge(m, src)
}
func (m *GetDocumentsByListAndContextsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsByListAndContextsRequest.Size(m)
}
func (m *GetDocumentsByListAndContextsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsByListAndContextsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsByListAndContextsRequest proto.InternalMessageInfo

func (m *GetDocumentsByListAndContextsRequest) GetListId() uint64 {
	if m != nil {
		return m.ListId
	}
	return 0
}

func (m *GetDocumentsByListAndContextsRequest) GetContextIds() []uint64 {
	if m != nil {
		return m.ContextIds
	}
	return nil
}

func (m *GetDocumentsByListAndContextsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetDocumentsByListAndContextsRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetDocumentsByListAndContextsResponse struct {
	Documents            []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetDocumentsByListAndContextsResponse) Reset()         { *m = GetDocumentsByListAndContextsResponse{} }
func (m *GetDocumentsByListAndContextsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsByListAndContextsResponse) ProtoMessage()    {}
func (*GetDocumentsByListAndContextsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{20}
}

func (m *GetDocumentsByListAndContextsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsByListAndContextsResponse.Unmarshal(m, b)
}
func (m *GetDocumentsByListAndContextsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsByListAndContextsResponse.Marshal(b, m, deterministic)
}
func (m *GetDocumentsByListAndContextsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsByListAndContextsResponse.Merge(m, src)
}
func (m *GetDocumentsByListAndContextsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsByListAndContextsResponse.Size(m)
}
func (m *GetDocumentsByListAndContextsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsByListAndContextsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsByListAndContextsResponse proto.InternalMessageInfo

func (m *GetDocumentsByListAndContextsResponse) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type GetCountByListAndContextsRequest struct {
	ListId               uint64   `protobuf:"varint,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	ContextIds           []uint64 `protobuf:"varint,2,rep,packed,name=context_ids,json=contextIds,proto3" json:"context_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCountByListAndContextsRequest) Reset()         { *m = GetCountByListAndContextsRequest{} }
func (m *GetCountByListAndContextsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCountByListAndContextsRequest) ProtoMessage()    {}
func (*GetCountByListAndContextsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{21}
}

func (m *GetCountByListAndContextsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountByListAndContextsRequest.Unmarshal(m, b)
}
func (m *GetCountByListAndContextsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountByListAndContextsRequest.Marshal(b, m, deterministic)
}
func (m *GetCountByListAndContextsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountByListAndContextsRequest.Merge(m, src)
}
func (m *GetCountByListAndContextsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCountByListAndContextsRequest.Size(m)
}
func (m *GetCountByListAndContextsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountByListAndContextsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountByListAndContextsRequest proto.InternalMessageInfo

func (m *GetCountByListAndContextsRequest) GetListId() uint64 {
	if m != nil {
		return m.ListId
	}
	return 0
}

func (m *GetCountByListAndContextsRequest) GetContextIds() []uint64 {
	if m != nil {
		return m.ContextIds
	}
	return nil
}

type GetCountByListAndContextsResponse struct {
	Count                *common.Count `protobuf:"bytes,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetCountByListAndContextsResponse) Reset()         { *m = GetCountByListAndContextsResponse{} }
func (m *GetCountByListAndContextsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCountByListAndContextsResponse) ProtoMessage()    {}
func (*GetCountByListAndContextsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{22}
}

func (m *GetCountByListAndContextsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountByListAndContextsResponse.Unmarshal(m, b)
}
func (m *GetCountByListAndContextsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountByListAndContextsResponse.Marshal(b, m, deterministic)
}
func (m *GetCountByListAndContextsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountByListAndContextsResponse.Merge(m, src)
}
func (m *GetCountByListAndContextsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCountByListAndContextsResponse.Size(m)
}
func (m *GetCountByListAndContextsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountByListAndContextsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountByListAndContextsResponse proto.InternalMessageInfo

func (m *GetCountByListAndContextsResponse) GetCount() *common.Count {
	if m != nil {
		return m.Count
	}
	return nil
}

func init() {
	proto.RegisterType((*Document)(nil), "message.task.Document")
	proto.RegisterType((*CreateRequest)(nil), "message.task.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "message.task.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "message.task.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "message.task.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "message.task.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "message.task.DeleteResponse")
	proto.RegisterType((*GetDocumentRequest)(nil), "message.task.GetDocumentRequest")
	proto.RegisterType((*GetDocumentResponse)(nil), "message.task.GetDocumentResponse")
	proto.RegisterType((*GetDocumentsRequest)(nil), "message.task.GetDocumentsRequest")
	proto.RegisterType((*GetDocumentsResponse)(nil), "message.task.GetDocumentsResponse")
	proto.RegisterType((*GetDocumentsAllRequest)(nil), "message.task.GetDocumentsAllRequest")
	proto.RegisterType((*GetDocumentsAllResponse)(nil), "message.task.GetDocumentsAllResponse")
	proto.RegisterType((*GetCountAllRequest)(nil), "message.task.GetCountAllRequest")
	proto.RegisterType((*GetCountAllResponse)(nil), "message.task.GetCountAllResponse")
	proto.RegisterType((*GetDocumentsByListRequest)(nil), "message.task.GetDocumentsByListRequest")
	proto.RegisterType((*GetDocumentsByListResponse)(nil), "message.task.GetDocumentsByListResponse")
	proto.RegisterType((*GetCountByListRequest)(nil), "message.task.GetCountByListRequest")
	proto.RegisterType((*GetCountByListResponse)(nil), "message.task.GetCountByListResponse")
	proto.RegisterType((*GetDocumentsByListAndContextsRequest)(nil), "message.task.GetDocumentsByListAndContextsRequest")
	proto.RegisterType((*GetDocumentsByListAndContextsResponse)(nil), "message.task.GetDocumentsByListAndContextsResponse")
	proto.RegisterType((*GetCountByListAndContextsRequest)(nil), "message.task.GetCountByListAndContextsRequest")
	proto.RegisterType((*GetCountByListAndContextsResponse)(nil), "message.task.GetCountByListAndContextsResponse")
}

func init() { proto.RegisterFile("message/task.proto", fileDescriptor_32fc8b087d8f54e9) }

var fileDescriptor_32fc8b087d8f54e9 = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xfb, 0x4e, 0x13, 0x4f,
	0x14, 0xfe, 0x6d, 0x5b, 0x4a, 0x7b, 0xf8, 0x95, 0x90, 0xb5, 0x94, 0x85, 0x10, 0xa9, 0x1b, 0x8c,
	0x4d, 0x0c, 0xad, 0x01, 0xf5, 0x4f, 0x93, 0x16, 0x88, 0x21, 0x21, 0x68, 0x36, 0x31, 0x31, 0x06,
	0x43, 0xb6, 0x3b, 0x43, 0x1d, 0xd9, 0xdd, 0xa9, 0x9d, 0x59, 0xd1, 0x17, 0xf1, 0x7d, 0xbc, 0xbc,
	0x87, 0x09, 0x4f, 0x62, 0xe6, 0xb6, 0x17, 0x90, 0x4b, 0xa8, 0xfc, 0xb7, 0xe7, 0x3b, 0x67, 0xbf,
	0xf3, 0x9d, 0xef, 0xcc, 0x5e, 0xc0, 0x8e, 0x30, 0x63, 0xfe, 0x08, 0xf7, 0xb8, 0xcf, 0x4e, 0xba,
	0xe3, 0x09, 0xe5, 0xd4, 0xfe, 0x5f, 0x63, 0x5d, 0x81, 0xad, 0x3c, 0x1f, 0x11, 0xfe, 0x21, 0x19,
	0x76, 0x03, 0x1a, 0xf5, 0xa2, 0x53, 0xc2, 0x4f, 0xe8, 0x69, 0x6f, 0x44, 0x37, 0x64, 0xe9, 0xc6,
	0x67, 0x3f, 0x24, 0xc8, 0xe7, 0x74, 0xc2, 0x7a, 0xe9, 0xa5, 0x62, 0x59, 0x69, 0x1a, 0xe6, 0x80,
	0x46, 0x11, 0x8d, 0x15, 0xea, 0x9e, 0x59, 0x50, 0xdb, 0xa1, 0x41, 0x12, 0xe1, 0x98, 0xdb, 0xf3,
	0x50, 0x22, 0xc8, 0xb1, 0xda, 0x56, 0xa7, 0xe2, 0x95, 0x08, 0xb2, 0x97, 0x60, 0x36, 0x24, 0x8c,
	0x1f, 0x11, 0xe4, 0x94, 0x24, 0x58, 0x15, 0xe1, 0x1e, 0xb2, 0x9b, 0x30, 0xc3, 0x09, 0x0f, 0xb1,
	0x53, 0x6e, 0x5b, 0x9d, 0xba, 0xa7, 0x02, 0x7b, 0x15, 0xea, 0x01, 0x8d, 0xc6, 0x21, 0xe6, 0x18,
	0x39, 0x95, 0xb6, 0xd5, 0xa9, 0x79, 0x19, 0x60, 0x2f, 0xc3, 0x2c, 0x8e, 0xfd, 0x61, 0x88, 0x91,
	0xf3, 0xfd, 0x85, 0x4c, 0x9a, 0xd8, 0xbe, 0x0f, 0x10, 0x4c, 0xb0, 0xcf, 0x31, 0x3a, 0xf2, 0xb9,
	0xf3, 0x43, 0x64, 0xcb, 0x5e, 0x5d, 0x43, 0x7d, 0x2e, 0xf2, 0xc9, 0x18, 0x99, 0xfc, 0x4f, 0x9d,
	0xd7, 0x90, 0xca, 0x23, 0x2c, 0xbb, 0x88, 0xfc, 0x2f, 0x9d, 0xd7, 0x50, 0x9f, 0xbb, 0x07, 0xd0,
	0xd8, 0x96, 0x64, 0x1e, 0xfe, 0x94, 0x60, 0xc6, 0xed, 0xb5, 0x6c, 0x30, 0x39, 0xed, 0xa0, 0x7a,
	0xf6, 0x7b, 0xad, 0xb4, 0xf0, 0x5f, 0x3a, 0xe0, 0xaa, 0x19, 0x50, 0xcc, 0x5d, 0x57, 0xe9, 0xb7,
	0x96, 0x1e, 0xd4, 0x3d, 0x84, 0x79, 0xc3, 0xc7, 0xc6, 0x34, 0x66, 0xd8, 0x6e, 0x41, 0x75, 0x82,
	0x59, 0x12, 0x72, 0xc9, 0x57, 0xf3, 0x74, 0x64, 0x6f, 0x42, 0x0d, 0x69, 0x77, 0x25, 0xd5, 0xdc,
	0x66, 0xab, 0x9b, 0xdf, 0x66, 0xd7, 0x78, 0xef, 0xa5, 0x75, 0xee, 0x2e, 0x34, 0xde, 0xc8, 0xd1,
	0x8c, 0xda, 0x56, 0xb6, 0x96, 0x54, 0xa8, 0x58, 0xcf, 0xb5, 0x22, 0x0d, 0xcd, 0x1d, 0x88, 0x7c,
	0x04, 0x8d, 0x1d, 0xe9, 0xef, 0x35, 0x22, 0x85, 0x0c, 0x53, 0x78, 0x07, 0x32, 0xd6, 0xc1, 0x7e,
	0x89, 0x79, 0x9a, 0xd0, 0x5a, 0xce, 0x9d, 0x63, 0x77, 0x0f, 0xee, 0x15, 0xaa, 0xb4, 0x90, 0x7c,
	0x43, 0xeb, 0xc6, 0x73, 0xe7, 0xa9, 0x98, 0xe9, 0xb8, 0x00, 0x65, 0x82, 0x98, 0x63, 0xb5, 0xcb,
	0x9d, 0x8a, 0x27, 0x2e, 0xdd, 0x7d, 0x68, 0x16, 0x0b, 0x75, 0xd3, 0xa7, 0x50, 0x37, 0x64, 0xaa,
	0xfe, 0xf2, 0xae, 0x59, 0xa1, 0x7b, 0x00, 0xad, 0x3c, 0x5b, 0x3f, 0x0c, 0x4d, 0xe7, 0x55, 0x98,
	0x09, 0x49, 0x44, 0xd4, 0x04, 0x0d, 0x65, 0xbd, 0x83, 0x3c, 0x05, 0x0a, 0xaf, 0xe9, 0xf1, 0x31,
	0xc3, 0xca, 0xd1, 0x86, 0xa7, 0x23, 0xf7, 0x15, 0x2c, 0x5d, 0xe0, 0x9b, 0x4a, 0x60, 0x53, 0x2e,
	0x62, 0x9b, 0x26, 0x31, 0xcf, 0xc4, 0xb9, 0x03, 0xe9, 0x56, 0x86, 0xea, 0x16, 0x8f, 0x61, 0x26,
	0x10, 0x98, 0x76, 0x7d, 0x31, 0xa5, 0xd7, 0xaf, 0x26, 0x79, 0x83, 0xa7, 0x6a, 0xdc, 0x8f, 0xb0,
	0x9c, 0x97, 0x3a, 0xf8, 0xba, 0x4f, 0x58, 0xba, 0xe9, 0xa5, 0x73, 0x0f, 0x72, 0xfe, 0x01, 0x56,
	0xb6, 0x94, 0xae, 0xb6, 0xa5, 0x5c, 0xb0, 0xc5, 0x83, 0x95, 0xbf, 0xf5, 0x9a, 0xca, 0x99, 0x27,
	0xb0, 0x68, 0x3c, 0xb8, 0x99, 0x76, 0x77, 0x57, 0x2e, 0xbb, 0x70, 0xc7, 0x6d, 0x8c, 0xfb, 0x66,
	0xc1, 0xfa, 0xc5, 0x69, 0xfa, 0x31, 0xda, 0xa6, 0x31, 0xc7, 0x5f, 0xb2, 0xc3, 0x7b, 0xa9, 0x89,
	0x6b, 0x30, 0x17, 0xa8, 0xda, 0x23, 0x71, 0xba, 0x4b, 0xf2, 0x74, 0x83, 0x86, 0xf6, 0x10, 0xcb,
	0x5c, 0x2e, 0x5f, 0xed, 0x72, 0xa5, 0xe0, 0xf2, 0x7b, 0x78, 0x78, 0x8d, 0xae, 0xa9, 0x0c, 0x3f,
	0x84, 0x76, 0xd1, 0xbe, 0x7f, 0x39, 0xb2, 0xfb, 0x1a, 0x1e, 0x5c, 0xc1, 0x7e, 0x8b, 0x3d, 0x0d,
	0x9e, 0xbd, 0xdb, 0xca, 0x7d, 0xd2, 0x87, 0x38, 0xa0, 0x2c, 0x39, 0x51, 0x3f, 0x00, 0x6c, 0xc3,
	0x1f, 0x93, 0x9e, 0xfc, 0x52, 0x8f, 0x70, 0xdc, 0xcb, 0xff, 0x1b, 0x0c, 0xab, 0x12, 0xde, 0xfa,
	0x13, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x45, 0x3d, 0x0b, 0x32, 0x08, 0x00, 0x00,
}
