// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/task.proto

package task // import "github.com/becosuke/tasks-api/protogen/message/task"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Document struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ListId               uint64   `protobuf:"varint,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Completed            bool     `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	Enabled              bool     `protobuf:"varint,8001,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt            int64    `protobuf:"varint,8002,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8003,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,8004,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_a89f47001a54ec80, []int{0}
}
func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (dst *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(dst, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Document) GetListId() uint64 {
	if m != nil {
		return m.ListId
	}
	return 0
}

func (m *Document) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Document) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *Document) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Document) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Document) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Document) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Document)(nil), "message.task.Document")
}

func init() { proto.RegisterFile("message/task.proto", fileDescriptor_task_a89f47001a54ec80) }

var fileDescriptor_task_a89f47001a54ec80 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x71, 0x92, 0xd6, 0xb6, 0x19, 0xc4, 0xc3, 0x22, 0xb8, 0x82, 0x48, 0xf0, 0x94, 0x8b,
	0xc9, 0xa1, 0x78, 0x15, 0x2a, 0x5e, 0xbc, 0xe6, 0xe8, 0xa5, 0x6c, 0x76, 0x86, 0xb8, 0x34, 0xc9,
	0x86, 0xee, 0xe4, 0x01, 0xfd, 0xf3, 0x24, 0x3e, 0x89, 0xec, 0x66, 0x8b, 0x3d, 0xce, 0xf7, 0x73,
	0x18, 0xf8, 0x81, 0xe8, 0xc9, 0x39, 0xd5, 0x52, 0xc5, 0xca, 0x1d, 0xca, 0xf1, 0x68, 0xd9, 0x8a,
	0xcb, 0xd8, 0x4a, 0xdf, 0x1e, 0x7e, 0x13, 0xd8, 0xbc, 0x5a, 0x3d, 0xf5, 0x34, 0xb0, 0xb8, 0x82,
	0xd4, 0xa0, 0x4c, 0xf2, 0xa4, 0x58, 0xd6, 0xa9, 0x41, 0x71, 0x03, 0xeb, 0xce, 0x38, 0xde, 0x1b,
	0x94, 0x69, 0x88, 0x2b, 0x7f, 0xbe, 0xa1, 0xb8, 0x86, 0x0b, 0x36, 0xdc, 0x91, 0x5c, 0xe4, 0x49,
	0x91, 0xd5, 0xf3, 0x21, 0xee, 0x20, 0xd3, 0xb6, 0x1f, 0x3b, 0x62, 0x42, 0xb9, 0xcc, 0x93, 0x62,
	0x53, 0xff, 0x07, 0x71, 0x0b, 0x6b, 0x1a, 0x54, 0xd3, 0x11, 0xca, 0xcf, 0xe7, 0x80, 0xa7, 0x5b,
	0xdc, 0x03, 0xe8, 0x23, 0x29, 0x26, 0xdc, 0x2b, 0x96, 0x5f, 0x5e, 0x17, 0x75, 0x16, 0xd3, 0x8e,
	0xbd, 0x4f, 0x23, 0x9e, 0xfc, 0x3b, 0x7a, 0x4c, 0xb3, 0x23, 0x85, 0x2f, 0xde, 0x7f, 0xa2, 0xc7,
	0xb4, 0xe3, 0x97, 0xa7, 0xf7, 0x6d, 0x6b, 0xf8, 0x63, 0x6a, 0x4a, 0x6d, 0xfb, 0xaa, 0x21, 0x6d,
	0xdd, 0x74, 0x98, 0x47, 0x71, 0x8f, 0x6a, 0x34, 0x55, 0x58, 0xa6, 0xa5, 0xa1, 0x3a, 0xdf, 0xab,
	0x59, 0x85, 0xbc, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xa0, 0xd1, 0x31, 0x46, 0x01, 0x00,
	0x00,
}
