// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/task.proto

package task

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Document struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt            int64    `protobuf:"varint,1001,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,1002,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,1003,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CompletedAt          int64    `protobuf:"varint,1004,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Enabled              bool     `protobuf:"varint,1101,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Updated              bool     `protobuf:"varint,1102,opt,name=updated,proto3" json:"updated,omitempty"`
	Deleted              bool     `protobuf:"varint,1103,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Completed            bool     `protobuf:"varint,1104,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_32fc8b087d8f54e9, []int{0}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Document) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Document) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Document) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Document) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *Document) GetCompletedAt() int64 {
	if m != nil {
		return m.CompletedAt
	}
	return 0
}

func (m *Document) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Document) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

func (m *Document) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Document) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func init() {
	proto.RegisterType((*Document)(nil), "message.task.Document")
}

func init() { proto.RegisterFile("message/task.proto", fileDescriptor_32fc8b087d8f54e9) }

var fileDescriptor_32fc8b087d8f54e9 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3b, 0x4e, 0xc4, 0x30,
	0x10, 0x86, 0xe5, 0xf0, 0xd8, 0xc4, 0xac, 0x28, 0x2c, 0x0a, 0x53, 0x80, 0xa2, 0xad, 0xd2, 0x90,
	0x14, 0x2b, 0x0e, 0x10, 0xc4, 0x09, 0x52, 0xd2, 0x20, 0xc7, 0x1e, 0x05, 0x6b, 0x93, 0x38, 0x5a,
	0x4f, 0x6e, 0xc4, 0x75, 0x78, 0x5c, 0x83, 0xc7, 0x21, 0x50, 0xd6, 0x93, 0xb0, 0xe5, 0xff, 0x7d,
	0xa3, 0xf9, 0xa5, 0x9f, 0x8b, 0x0e, 0xbc, 0x57, 0x0d, 0x14, 0xa8, 0xfc, 0x2e, 0x1f, 0xf6, 0x0e,
	0x9d, 0x58, 0x13, 0xcb, 0x27, 0xb6, 0x79, 0x8d, 0x78, 0xfc, 0xe8, 0xf4, 0xd8, 0x41, 0x8f, 0xe2,
	0x92, 0x47, 0xd6, 0x48, 0x96, 0xb2, 0xec, 0xb4, 0x8a, 0xac, 0x11, 0x57, 0xfc, 0x0c, 0x2d, 0xb6,
	0x20, 0xa3, 0x94, 0x65, 0x49, 0x15, 0x82, 0xb8, 0xe5, 0x5c, 0xef, 0x41, 0x21, 0x98, 0x67, 0x85,
	0xf2, 0x6b, 0x95, 0xb2, 0xec, 0xa4, 0x4a, 0x08, 0x95, 0x38, 0xf9, 0x71, 0x30, 0xb3, 0xff, 0x26,
	0x4f, 0x28, 0x78, 0x03, 0x2d, 0x90, 0xff, 0x21, 0x4f, 0xa8, 0x44, 0xb1, 0xe1, 0x6b, 0xed, 0xba,
	0x61, 0xb9, 0xf8, 0x0d, 0x17, 0x17, 0x0b, 0x2c, 0x51, 0x5c, 0xf3, 0x15, 0xf4, 0xaa, 0x6e, 0xc1,
	0xc8, 0xb7, 0x38, 0x65, 0x59, 0x5c, 0xcd, 0x79, 0x52, 0xd4, 0x25, 0xdf, 0x49, 0x51, 0x9e, 0x14,
	0xd5, 0xc8, 0x0f, 0x52, 0x94, 0xc5, 0x0d, 0x4f, 0x96, 0xff, 0xf2, 0x33, 0xc8, 0x7f, 0xf2, 0x70,
	0xff, 0xb4, 0x6d, 0x2c, 0xbe, 0x8c, 0x75, 0xae, 0x5d, 0x57, 0xd4, 0xa0, 0x9d, 0x1f, 0x77, 0x61,
	0x56, 0x7f, 0xa7, 0x06, 0x5b, 0x1c, 0xb6, 0x6d, 0xa0, 0x2f, 0x8e, 0x17, 0xaf, 0xcf, 0x0f, 0x78,
	0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xdf, 0x73, 0x20, 0x88, 0x01, 0x00, 0x00,
}
