// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/list.proto

package list // import "github.com/becosuke/tasks-api/protogen/message/list"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Document struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Enabled              bool     `protobuf:"varint,8001,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt            int64    `protobuf:"varint,8002,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8003,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,8004,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_list_90ec48171ea8b202, []int{0}
}
func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (dst *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(dst, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Document) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Document) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Document) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Document) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Document) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Document)(nil), "message.list.Document")
}

func init() { proto.RegisterFile("message/list.proto", fileDescriptor_list_90ec48171ea8b202) }

var fileDescriptor_list_90ec48171ea8b202 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0xbb, 0x4e, 0x86, 0x30,
	0x18, 0xc6, 0xf1, 0x14, 0x4f, 0x1f, 0x8d, 0x71, 0x68, 0x1c, 0xea, 0x62, 0x88, 0x13, 0x8b, 0x74,
	0x20, 0xae, 0x26, 0x18, 0xaf, 0xa0, 0xa3, 0x8b, 0xe9, 0xe1, 0x0d, 0x36, 0x14, 0x4a, 0xe8, 0xdb,
	0xab, 0xf2, 0x2a, 0x3c, 0x5c, 0x98, 0x01, 0x4a, 0xe2, 0xf8, 0xfc, 0x7f, 0xd3, 0x43, 0xd9, 0x08,
	0x31, 0xaa, 0x1e, 0x84, 0x77, 0x11, 0x9b, 0x79, 0x09, 0x18, 0xd8, 0x75, 0x6e, 0xcd, 0xda, 0x1e,
	0x3e, 0x09, 0x3d, 0xbd, 0x06, 0x93, 0x46, 0x98, 0x90, 0xdd, 0xd0, 0xc2, 0x59, 0x4e, 0x2a, 0x52,
	0x9f, 0xcb, 0xc2, 0x59, 0x76, 0x4b, 0x2f, 0xd0, 0xa1, 0x07, 0x5e, 0x54, 0xa4, 0x2e, 0xe5, 0x3e,
	0xd8, 0x1d, 0xbd, 0x82, 0x49, 0x69, 0x0f, 0x96, 0x7f, 0x3d, 0x57, 0xa4, 0x3e, 0xc9, 0x63, 0xb3,
	0x7b, 0x4a, 0xcd, 0x02, 0x0a, 0xc1, 0xbe, 0x2b, 0xe4, 0xdf, 0xab, 0x9e, 0xc9, 0x32, 0xa7, 0x0e,
	0x57, 0x4f, 0xb3, 0x3d, 0xfc, 0x27, 0x7b, 0x4e, 0xbb, 0x5b, 0xf0, 0x90, 0xfd, 0x37, 0x7b, 0x4e,
	0x1d, 0xbe, 0x3c, 0xbd, 0xb5, 0xbd, 0xc3, 0x8f, 0xa4, 0x1b, 0x13, 0x46, 0xa1, 0xc1, 0x84, 0x98,
	0x06, 0x10, 0xa8, 0xe2, 0x10, 0x1f, 0xd5, 0xec, 0xc4, 0x76, 0xb1, 0x87, 0x49, 0xfc, 0x3f, 0xae,
	0x2f, 0xb7, 0xdc, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x37, 0xd4, 0x04, 0x0f, 0x01, 0x00,
	0x00,
}
