// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/list.proto

package list

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Document struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt            int64    `protobuf:"varint,1001,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,1002,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,1003,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Enabled              bool     `protobuf:"varint,1101,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Updated              bool     `protobuf:"varint,1102,opt,name=updated,proto3" json:"updated,omitempty"`
	Deleted              bool     `protobuf:"varint,1103,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c5de5fa04d10dd8, []int{0}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Document) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Document) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Document) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Document) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *Document) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Document) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

func (m *Document) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func init() {
	proto.RegisterType((*Document)(nil), "message.list.Document")
}

func init() { proto.RegisterFile("message/list.proto", fileDescriptor_5c5de5fa04d10dd8) }

var fileDescriptor_5c5de5fa04d10dd8 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0x3b, 0x4e, 0x03, 0x31,
	0x10, 0xc6, 0x71, 0x79, 0x79, 0x64, 0x63, 0x21, 0x0a, 0x8b, 0xc2, 0x34, 0x68, 0x45, 0xb5, 0x0d,
	0xeb, 0x22, 0xe2, 0x00, 0x41, 0x9c, 0xc0, 0x25, 0x0d, 0xf2, 0x63, 0xb4, 0x58, 0xf1, 0xae, 0x57,
	0xf1, 0xf8, 0x98, 0xc0, 0x19, 0x28, 0x81, 0x4b, 0x20, 0x27, 0x13, 0x89, 0xf2, 0xfb, 0xff, 0xa4,
	0x29, 0x86, 0x8b, 0x09, 0x72, 0x36, 0x23, 0xa8, 0x18, 0x32, 0x0e, 0xcb, 0x3e, 0x61, 0x12, 0x57,
	0xd4, 0x86, 0xda, 0xee, 0xbf, 0x18, 0x6f, 0x9f, 0x93, 0x2b, 0x13, 0xcc, 0x28, 0xae, 0x79, 0x13,
	0xbc, 0x64, 0x1d, 0xeb, 0xcf, 0x75, 0x13, 0xbc, 0xb8, 0xe1, 0x17, 0x18, 0x30, 0x82, 0x6c, 0x3a,
	0xd6, 0xaf, 0xf5, 0x71, 0x88, 0x3b, 0xce, 0xdd, 0x1e, 0x0c, 0x82, 0x7f, 0x35, 0x28, 0xbf, 0x57,
	0x1d, 0xeb, 0xcf, 0xf4, 0x9a, 0xd2, 0x16, 0xab, 0x97, 0xc5, 0x9f, 0xfc, 0x87, 0x9c, 0xd2, 0xd1,
	0x3d, 0x44, 0x20, 0xff, 0x25, 0xa7, 0xb4, 0x45, 0x71, 0xcb, 0x57, 0x30, 0x1b, 0x1b, 0xc1, 0xcb,
	0xf7, 0xb6, 0x63, 0x7d, 0xab, 0x4f, 0xbb, 0x12, 0xdd, 0x91, 0x1f, 0x44, 0xb4, 0x2b, 0xd1, 0x09,
	0xf9, 0x49, 0x44, 0xfb, 0xe9, 0xf1, 0x65, 0x33, 0x06, 0x7c, 0x2b, 0x76, 0x70, 0x69, 0x52, 0x16,
	0x5c, 0xca, 0x65, 0x07, 0x0a, 0x4d, 0xde, 0xe5, 0x07, 0xb3, 0x04, 0x75, 0x78, 0xcc, 0x08, 0xb3,
	0xfa, 0xff, 0x2e, 0x7b, 0x79, 0xc8, 0x9b, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x01, 0x47,
	0x53, 0x45, 0x01, 0x00, 0x00,
}
