// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/context.proto

package context

import (
	fmt "fmt"
	common "github.com/becosuke/tasks-api/protogen/message/common"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Document struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Enabled              bool     `protobuf:"varint,8001,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt            int64    `protobuf:"varint,8002,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8003,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,8004,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{0}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Document) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Document) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Document) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Document) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Document) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type CreateRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CreateResponse struct {
	Result               bool      `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Document             *Document `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *CreateResponse) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type UpdateRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{3}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type UpdateResponse struct {
	Result               bool      `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Document             *Document `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{4}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *UpdateResponse) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type DeleteRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{5}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponse struct {
	Result               bool      `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Document             *Document `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{6}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *DeleteResponse) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type GetDocumentRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentRequest) Reset()         { *m = GetDocumentRequest{} }
func (m *GetDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentRequest) ProtoMessage()    {}
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{7}
}

func (m *GetDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentRequest.Unmarshal(m, b)
}
func (m *GetDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentRequest.Marshal(b, m, deterministic)
}
func (m *GetDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentRequest.Merge(m, src)
}
func (m *GetDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentRequest.Size(m)
}
func (m *GetDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentRequest proto.InternalMessageInfo

func (m *GetDocumentRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetDocumentResponse struct {
	Document             *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetDocumentResponse) Reset()         { *m = GetDocumentResponse{} }
func (m *GetDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*GetDocumentResponse) ProtoMessage()    {}
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{8}
}

func (m *GetDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentResponse.Unmarshal(m, b)
}
func (m *GetDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentResponse.Marshal(b, m, deterministic)
}
func (m *GetDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentResponse.Merge(m, src)
}
func (m *GetDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_GetDocumentResponse.Size(m)
}
func (m *GetDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentResponse proto.InternalMessageInfo

func (m *GetDocumentResponse) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type GetDocumentsRequest struct {
	Ids                  []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentsRequest) Reset()         { *m = GetDocumentsRequest{} }
func (m *GetDocumentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsRequest) ProtoMessage()    {}
func (*GetDocumentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{9}
}

func (m *GetDocumentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsRequest.Unmarshal(m, b)
}
func (m *GetDocumentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsRequest.Marshal(b, m, deterministic)
}
func (m *GetDocumentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsRequest.Merge(m, src)
}
func (m *GetDocumentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsRequest.Size(m)
}
func (m *GetDocumentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsRequest proto.InternalMessageInfo

func (m *GetDocumentsRequest) GetIds() []uint64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetDocumentsResponse struct {
	Documents            []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetDocumentsResponse) Reset()         { *m = GetDocumentsResponse{} }
func (m *GetDocumentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsResponse) ProtoMessage()    {}
func (*GetDocumentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{10}
}

func (m *GetDocumentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsResponse.Unmarshal(m, b)
}
func (m *GetDocumentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsResponse.Marshal(b, m, deterministic)
}
func (m *GetDocumentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsResponse.Merge(m, src)
}
func (m *GetDocumentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsResponse.Size(m)
}
func (m *GetDocumentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsResponse proto.InternalMessageInfo

func (m *GetDocumentsResponse) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type GetDocumentsAllRequest struct {
	Limit                uint32   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentsAllRequest) Reset()         { *m = GetDocumentsAllRequest{} }
func (m *GetDocumentsAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsAllRequest) ProtoMessage()    {}
func (*GetDocumentsAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{11}
}

func (m *GetDocumentsAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsAllRequest.Unmarshal(m, b)
}
func (m *GetDocumentsAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsAllRequest.Marshal(b, m, deterministic)
}
func (m *GetDocumentsAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsAllRequest.Merge(m, src)
}
func (m *GetDocumentsAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsAllRequest.Size(m)
}
func (m *GetDocumentsAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsAllRequest proto.InternalMessageInfo

func (m *GetDocumentsAllRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetDocumentsAllRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetDocumentsAllResponse struct {
	Documents            []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetDocumentsAllResponse) Reset()         { *m = GetDocumentsAllResponse{} }
func (m *GetDocumentsAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsAllResponse) ProtoMessage()    {}
func (*GetDocumentsAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{12}
}

func (m *GetDocumentsAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsAllResponse.Unmarshal(m, b)
}
func (m *GetDocumentsAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsAllResponse.Marshal(b, m, deterministic)
}
func (m *GetDocumentsAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsAllResponse.Merge(m, src)
}
func (m *GetDocumentsAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsAllResponse.Size(m)
}
func (m *GetDocumentsAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsAllResponse proto.InternalMessageInfo

func (m *GetDocumentsAllResponse) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type GetCountAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCountAllRequest) Reset()         { *m = GetCountAllRequest{} }
func (m *GetCountAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetCountAllRequest) ProtoMessage()    {}
func (*GetCountAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{13}
}

func (m *GetCountAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountAllRequest.Unmarshal(m, b)
}
func (m *GetCountAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountAllRequest.Marshal(b, m, deterministic)
}
func (m *GetCountAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountAllRequest.Merge(m, src)
}
func (m *GetCountAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetCountAllRequest.Size(m)
}
func (m *GetCountAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountAllRequest proto.InternalMessageInfo

type GetCountAllResponse struct {
	Count                *common.Count `protobuf:"bytes,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetCountAllResponse) Reset()         { *m = GetCountAllResponse{} }
func (m *GetCountAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetCountAllResponse) ProtoMessage()    {}
func (*GetCountAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9b282443f5224df, []int{14}
}

func (m *GetCountAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCountAllResponse.Unmarshal(m, b)
}
func (m *GetCountAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCountAllResponse.Marshal(b, m, deterministic)
}
func (m *GetCountAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCountAllResponse.Merge(m, src)
}
func (m *GetCountAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetCountAllResponse.Size(m)
}
func (m *GetCountAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCountAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCountAllResponse proto.InternalMessageInfo

func (m *GetCountAllResponse) GetCount() *common.Count {
	if m != nil {
		return m.Count
	}
	return nil
}

func init() {
	proto.RegisterType((*Document)(nil), "message.context.Document")
	proto.RegisterType((*CreateRequest)(nil), "message.context.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "message.context.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "message.context.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "message.context.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "message.context.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "message.context.DeleteResponse")
	proto.RegisterType((*GetDocumentRequest)(nil), "message.context.GetDocumentRequest")
	proto.RegisterType((*GetDocumentResponse)(nil), "message.context.GetDocumentResponse")
	proto.RegisterType((*GetDocumentsRequest)(nil), "message.context.GetDocumentsRequest")
	proto.RegisterType((*GetDocumentsResponse)(nil), "message.context.GetDocumentsResponse")
	proto.RegisterType((*GetDocumentsAllRequest)(nil), "message.context.GetDocumentsAllRequest")
	proto.RegisterType((*GetDocumentsAllResponse)(nil), "message.context.GetDocumentsAllResponse")
	proto.RegisterType((*GetCountAllRequest)(nil), "message.context.GetCountAllRequest")
	proto.RegisterType((*GetCountAllResponse)(nil), "message.context.GetCountAllResponse")
}

func init() { proto.RegisterFile("message/context.proto", fileDescriptor_e9b282443f5224df) }

var fileDescriptor_e9b282443f5224df = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdd, 0x8a, 0xd3, 0x40,
	0x18, 0x35, 0xed, 0x6e, 0x6d, 0x3f, 0xc9, 0xba, 0xc4, 0x6e, 0xcd, 0x2e, 0x8b, 0x96, 0x41, 0xb0,
	0x20, 0x4d, 0x40, 0xf1, 0xe7, 0x4a, 0x68, 0x77, 0xc5, 0x1b, 0x51, 0x18, 0x10, 0xc4, 0x9b, 0x25,
	0xcd, 0x7c, 0x5b, 0x87, 0x26, 0x99, 0xda, 0x99, 0xb8, 0xbe, 0x93, 0x4f, 0xe1, 0xcf, 0x7b, 0x08,
	0x3e, 0x89, 0x64, 0x7e, 0x9a, 0xb4, 0x8a, 0x22, 0xb2, 0x77, 0x99, 0x73, 0x4e, 0xce, 0x77, 0xe6,
	0x24, 0x7c, 0x70, 0x90, 0xa3, 0x94, 0xc9, 0x1c, 0xe3, 0x54, 0x14, 0x0a, 0x3f, 0xaa, 0x68, 0xb9,
	0x12, 0x4a, 0x04, 0xd7, 0x2d, 0x1c, 0x59, 0xf8, 0xe8, 0xd1, 0x9c, 0xab, 0x77, 0xe5, 0x2c, 0x4a,
	0x45, 0x1e, 0xe7, 0x17, 0x5c, 0x2d, 0xc4, 0x45, 0x3c, 0x17, 0x63, 0xad, 0x1e, 0x7f, 0x48, 0x32,
	0xce, 0x12, 0x25, 0x56, 0x32, 0x5e, 0x3f, 0x1a, 0xa3, 0xa3, 0x7e, 0xed, 0x9f, 0xe7, 0xa2, 0x30,
	0x28, 0xf9, 0xe4, 0x41, 0xf7, 0x54, 0xa4, 0x65, 0x8e, 0x85, 0x0a, 0xf6, 0xa0, 0xc5, 0x59, 0xe8,
	0x0d, 0xbd, 0xd1, 0x0e, 0x6d, 0x71, 0x16, 0xf4, 0x61, 0x57, 0x71, 0x95, 0x61, 0xd8, 0x1a, 0x7a,
	0xa3, 0x1e, 0x35, 0x87, 0xe0, 0x10, 0xae, 0x62, 0x91, 0xcc, 0x32, 0x64, 0xe1, 0xe7, 0xa7, 0x43,
	0x6f, 0xd4, 0xa5, 0xee, 0x1c, 0xdc, 0x02, 0x48, 0x57, 0x98, 0x28, 0x64, 0x67, 0x89, 0x0a, 0xbf,
	0x54, 0x6c, 0x9b, 0xf6, 0x2c, 0x34, 0x51, 0x15, 0x5f, 0x2e, 0x99, 0xe3, 0xbf, 0x5a, 0xde, 0x42,
	0x86, 0x67, 0x98, 0xa1, 0xe5, 0xbf, 0x59, 0xde, 0x42, 0x13, 0x45, 0xc6, 0xe0, 0x9f, 0x68, 0x33,
	0x8a, 0xef, 0x4b, 0x94, 0x2a, 0x38, 0x76, 0x09, 0xab, 0xd0, 0xbd, 0x69, 0xe7, 0xc7, 0xf7, 0xdb,
	0xad, 0x37, 0x9e, 0x4d, 0x4a, 0xce, 0x60, 0xcf, 0xc9, 0xe5, 0x52, 0x14, 0x12, 0x83, 0x01, 0x74,
	0x56, 0x28, 0xcb, 0x4c, 0xe9, 0x17, 0xba, 0xd4, 0x9e, 0x82, 0x87, 0xd0, 0x65, 0xb6, 0x05, 0x7d,
	0xd9, 0x6b, 0xf7, 0x0f, 0xa3, 0xad, 0xe2, 0x23, 0x57, 0x13, 0x5d, 0x4b, 0xc9, 0x33, 0xf0, 0x5f,
	0xeb, 0xf0, 0x2e, 0xcf, 0xa0, 0x6e, 0xd0, 0x84, 0xd9, 0xbf, 0xa2, 0x9b, 0x3c, 0xde, 0x68, 0xf2,
	0x37, 0x39, 0x9d, 0xcd, 0xe5, 0xe4, 0xbc, 0x0b, 0xfe, 0xa9, 0x2e, 0xf1, 0x2f, 0x39, 0xab, 0x24,
	0x4e, 0x78, 0x39, 0x49, 0xee, 0x40, 0xf0, 0x1c, 0xd5, 0x9a, 0xb0, 0x71, 0xb6, 0x7e, 0x3c, 0xf2,
	0x02, 0x6e, 0x6c, 0xa8, 0x6c, 0x96, 0xe6, 0x4c, 0xef, 0x5f, 0x6e, 0xdf, 0x74, 0x93, 0x6e, 0xe8,
	0x3e, 0xb4, 0x39, 0x93, 0xa1, 0x37, 0x6c, 0x8f, 0x76, 0x68, 0xf5, 0x48, 0x5e, 0x41, 0x7f, 0x53,
	0x68, 0xe7, 0x3e, 0x86, 0x9e, 0x33, 0x33, 0xfa, 0x3f, 0x0e, 0xae, 0xb5, 0xe4, 0x25, 0x0c, 0x9a,
	0x86, 0x93, 0x2c, 0x6b, 0xfc, 0xb8, 0x19, 0xcf, 0xb9, 0xb9, 0x87, 0x6f, 0xbe, 0x41, 0xc8, 0xa8,
	0x01, 0xab, 0xd2, 0xc5, 0xf9, 0xb9, 0x44, 0x53, 0xad, 0x4f, 0xed, 0x89, 0x50, 0xb8, 0xf9, 0x8b,
	0xdf, 0xff, 0x66, 0xec, 0xeb, 0x2f, 0x72, 0x22, 0xca, 0x42, 0xd5, 0xf9, 0xc8, 0x54, 0x77, 0x56,
	0xa3, 0x76, 0xca, 0x3d, 0xd8, 0x4d, 0x2b, 0xcc, 0xd6, 0x7f, 0xd0, 0x98, 0xa0, 0x97, 0x8a, 0x7e,
	0x81, 0x1a, 0xcd, 0xf4, 0xc9, 0xdb, 0xe6, 0xae, 0x9a, 0x61, 0x2a, 0x64, 0xb9, 0xc0, 0x58, 0x25,
	0x72, 0x21, 0xc7, 0xc9, 0x92, 0xc7, 0x7a, 0x05, 0xcd, 0xb1, 0x88, 0xb7, 0x56, 0xdf, 0xac, 0xa3,
	0x99, 0x07, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xbf, 0x62, 0xf8, 0x14, 0x05, 0x00, 0x00,
}
