// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3500a110946dc12, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Id struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3500a110946dc12, []int{1}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Ids struct {
	Ids                  []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ids) Reset()         { *m = Ids{} }
func (m *Ids) String() string { return proto.CompactTextString(m) }
func (*Ids) ProtoMessage()    {}
func (*Ids) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3500a110946dc12, []int{2}
}

func (m *Ids) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ids.Unmarshal(m, b)
}
func (m *Ids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ids.Marshal(b, m, deterministic)
}
func (m *Ids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ids.Merge(m, src)
}
func (m *Ids) XXX_Size() int {
	return xxx_messageInfo_Ids.Size(m)
}
func (m *Ids) XXX_DiscardUnknown() {
	xxx_messageInfo_Ids.DiscardUnknown(m)
}

var xxx_messageInfo_Ids proto.InternalMessageInfo

func (m *Ids) GetIds() []uint64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Pagination struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3500a110946dc12, []int{3}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Pagination) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type IdPagination struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdPagination) Reset()         { *m = IdPagination{} }
func (m *IdPagination) String() string { return proto.CompactTextString(m) }
func (*IdPagination) ProtoMessage()    {}
func (*IdPagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3500a110946dc12, []int{4}
}

func (m *IdPagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdPagination.Unmarshal(m, b)
}
func (m *IdPagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdPagination.Marshal(b, m, deterministic)
}
func (m *IdPagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdPagination.Merge(m, src)
}
func (m *IdPagination) XXX_Size() int {
	return xxx_messageInfo_IdPagination.Size(m)
}
func (m *IdPagination) XXX_DiscardUnknown() {
	xxx_messageInfo_IdPagination.DiscardUnknown(m)
}

var xxx_messageInfo_IdPagination proto.InternalMessageInfo

func (m *IdPagination) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IdPagination) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *IdPagination) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Count struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Count) Reset()         { *m = Count{} }
func (m *Count) String() string { return proto.CompactTextString(m) }
func (*Count) ProtoMessage()    {}
func (*Count) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3500a110946dc12, []int{5}
}

func (m *Count) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Count.Unmarshal(m, b)
}
func (m *Count) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Count.Marshal(b, m, deterministic)
}
func (m *Count) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Count.Merge(m, src)
}
func (m *Count) XXX_Size() int {
	return xxx_messageInfo_Count.Size(m)
}
func (m *Count) XXX_DiscardUnknown() {
	xxx_messageInfo_Count.DiscardUnknown(m)
}

var xxx_messageInfo_Count proto.InternalMessageInfo

func (m *Count) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Coordinate struct {
	Vertical             float64  `protobuf:"fixed64,1,opt,name=vertical,proto3" json:"vertical,omitempty"`
	Horizontal           float64  `protobuf:"fixed64,2,opt,name=horizontal,proto3" json:"horizontal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3500a110946dc12, []int{6}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetVertical() float64 {
	if m != nil {
		return m.Vertical
	}
	return 0
}

func (m *Coordinate) GetHorizontal() float64 {
	if m != nil {
		return m.Horizontal
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "message.common.Empty")
	proto.RegisterType((*Id)(nil), "message.common.Id")
	proto.RegisterType((*Ids)(nil), "message.common.Ids")
	proto.RegisterType((*Pagination)(nil), "message.common.Pagination")
	proto.RegisterType((*IdPagination)(nil), "message.common.IdPagination")
	proto.RegisterType((*Count)(nil), "message.common.Count")
	proto.RegisterType((*Coordinate)(nil), "message.common.Coordinate")
}

func init() { proto.RegisterFile("message/common.proto", fileDescriptor_f3500a110946dc12) }

var fileDescriptor_f3500a110946dc12 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0x69, 0xbb, 0x4e, 0xf9, 0x90, 0x21, 0xa1, 0x68, 0x11, 0x94, 0x91, 0xd3, 0x2e, 0xae,
	0x07, 0x11, 0xc1, 0xa3, 0x43, 0xb0, 0xe0, 0x41, 0x7a, 0xf4, 0x96, 0x36, 0x59, 0xf7, 0xb1, 0x36,
	0x5f, 0x69, 0x52, 0x41, 0xff, 0x7a, 0x49, 0x5a, 0x74, 0x13, 0x6f, 0xdf, 0x7b, 0xc9, 0xfb, 0x3d,
	0x78, 0x90, 0xb4, 0xca, 0x18, 0x51, 0xab, 0xac, 0xa2, 0xb6, 0x25, 0xbd, 0xee, 0x7a, 0xb2, 0xc4,
	0x16, 0x93, 0xbb, 0x1e, 0x5d, 0x7e, 0x02, 0xf1, 0x73, 0xdb, 0xd9, 0x4f, 0x9e, 0x40, 0x98, 0x4b,
	0xb6, 0x80, 0x10, 0x65, 0x1a, 0x2c, 0x83, 0xd5, 0xac, 0x08, 0x51, 0xf2, 0x4b, 0x88, 0x72, 0x69,
	0xd8, 0x39, 0x44, 0x28, 0x4d, 0x1a, 0x2c, 0xa3, 0xd5, 0xac, 0x70, 0x27, 0x7f, 0x04, 0x78, 0x13,
	0x35, 0x6a, 0x61, 0x91, 0x34, 0x4b, 0x20, 0x6e, 0xb0, 0x45, 0xeb, 0x93, 0x71, 0x31, 0x0a, 0x76,
	0x01, 0x73, 0xda, 0x6e, 0x8d, 0xb2, 0x69, 0xe8, 0xed, 0x49, 0xf1, 0x57, 0x38, 0xcb, 0xe5, 0x41,
	0xfa, 0x4f, 0xe9, 0x2f, 0x2d, 0xfc, 0x9f, 0x16, 0x1d, 0xd1, 0xae, 0x21, 0xde, 0xd0, 0xa0, 0xad,
	0x8b, 0x55, 0xee, 0x98, 0x48, 0xa3, 0xe0, 0x2f, 0x00, 0x1b, 0xa2, 0x5e, 0xba, 0x32, 0xc5, 0xae,
	0xe0, 0xf4, 0x43, 0xf5, 0x16, 0x2b, 0xd1, 0xf8, 0x6f, 0x41, 0xf1, 0xa3, 0xd9, 0x0d, 0xc0, 0x8e,
	0x7a, 0xfc, 0x22, 0x6d, 0x45, 0xe3, 0xbb, 0x83, 0xe2, 0xc0, 0x79, 0x7a, 0x78, 0xbf, 0xaf, 0xd1,
	0xee, 0x86, 0xd2, 0x6d, 0x97, 0x95, 0xaa, 0x22, 0x33, 0xec, 0x55, 0x66, 0x85, 0xd9, 0x9b, 0x5b,
	0xd1, 0x61, 0xe6, 0x17, 0xae, 0x95, 0xce, 0x8e, 0x97, 0x2f, 0xe7, 0xfe, 0xe1, 0xee, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0xc5, 0x5a, 0x7f, 0xc1, 0x92, 0x01, 0x00, 0x00,
}
