// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/common.proto

package common // import "github.com/becosuke/tasks-api/protogen/message/common"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_5c796b936f910dec, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Id struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_5c796b936f910dec, []int{1}
}
func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (dst *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(dst, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Ids struct {
	Ids                  []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ids) Reset()         { *m = Ids{} }
func (m *Ids) String() string { return proto.CompactTextString(m) }
func (*Ids) ProtoMessage()    {}
func (*Ids) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_5c796b936f910dec, []int{2}
}
func (m *Ids) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ids.Unmarshal(m, b)
}
func (m *Ids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ids.Marshal(b, m, deterministic)
}
func (dst *Ids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ids.Merge(dst, src)
}
func (m *Ids) XXX_Size() int {
	return xxx_messageInfo_Ids.Size(m)
}
func (m *Ids) XXX_DiscardUnknown() {
	xxx_messageInfo_Ids.DiscardUnknown(m)
}

var xxx_messageInfo_Ids proto.InternalMessageInfo

func (m *Ids) GetIds() []uint64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Pagination struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_5c796b936f910dec, []int{3}
}
func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (dst *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(dst, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Pagination) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type IdPagination struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdPagination) Reset()         { *m = IdPagination{} }
func (m *IdPagination) String() string { return proto.CompactTextString(m) }
func (*IdPagination) ProtoMessage()    {}
func (*IdPagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_5c796b936f910dec, []int{4}
}
func (m *IdPagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdPagination.Unmarshal(m, b)
}
func (m *IdPagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdPagination.Marshal(b, m, deterministic)
}
func (dst *IdPagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdPagination.Merge(dst, src)
}
func (m *IdPagination) XXX_Size() int {
	return xxx_messageInfo_IdPagination.Size(m)
}
func (m *IdPagination) XXX_DiscardUnknown() {
	xxx_messageInfo_IdPagination.DiscardUnknown(m)
}

var xxx_messageInfo_IdPagination proto.InternalMessageInfo

func (m *IdPagination) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IdPagination) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *IdPagination) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Count struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Count) Reset()         { *m = Count{} }
func (m *Count) String() string { return proto.CompactTextString(m) }
func (*Count) ProtoMessage()    {}
func (*Count) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_5c796b936f910dec, []int{5}
}
func (m *Count) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Count.Unmarshal(m, b)
}
func (m *Count) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Count.Marshal(b, m, deterministic)
}
func (dst *Count) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Count.Merge(dst, src)
}
func (m *Count) XXX_Size() int {
	return xxx_messageInfo_Count.Size(m)
}
func (m *Count) XXX_DiscardUnknown() {
	xxx_messageInfo_Count.DiscardUnknown(m)
}

var xxx_messageInfo_Count proto.InternalMessageInfo

func (m *Count) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Result struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_5c796b936f910dec, []int{6}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*Empty)(nil), "message.common.Empty")
	proto.RegisterType((*Id)(nil), "message.common.Id")
	proto.RegisterType((*Ids)(nil), "message.common.Ids")
	proto.RegisterType((*Pagination)(nil), "message.common.Pagination")
	proto.RegisterType((*IdPagination)(nil), "message.common.IdPagination")
	proto.RegisterType((*Count)(nil), "message.common.Count")
	proto.RegisterType((*Result)(nil), "message.common.Result")
}

func init() { proto.RegisterFile("message/common.proto", fileDescriptor_common_5c796b936f910dec) }

var fileDescriptor_common_5c796b936f910dec = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4b, 0xc4, 0x30,
	0x18, 0xc5, 0x69, 0x7b, 0xad, 0xf2, 0x21, 0x87, 0x84, 0xa2, 0x5d, 0x84, 0x92, 0xe9, 0x16, 0x2f,
	0x83, 0x88, 0xe0, 0xa8, 0x38, 0x14, 0x1c, 0x24, 0xa3, 0x5b, 0xda, 0xe4, 0xea, 0xc7, 0x5d, 0x92,
	0x72, 0x5f, 0x3a, 0xf8, 0xdf, 0x4b, 0xd3, 0x82, 0x9e, 0xdc, 0xf6, 0xde, 0x4b, 0xde, 0xef, 0x83,
	0x07, 0xa5, 0x35, 0x44, 0xaa, 0x37, 0xa2, 0xf3, 0xd6, 0x7a, 0xb7, 0x1d, 0x8e, 0x3e, 0x78, 0xb6,
	0x5e, 0xd2, 0xed, 0x9c, 0xf2, 0x0b, 0xc8, 0xdf, 0xec, 0x10, 0xbe, 0x79, 0x09, 0x69, 0xa3, 0xd9,
	0x1a, 0x52, 0xd4, 0x55, 0x52, 0x27, 0x9b, 0x95, 0x4c, 0x51, 0xf3, 0x5b, 0xc8, 0x1a, 0x4d, 0xec,
	0x1a, 0x32, 0xd4, 0x54, 0x25, 0x75, 0xb6, 0x59, 0xc9, 0x49, 0xf2, 0x67, 0x80, 0x0f, 0xd5, 0xa3,
	0x53, 0x01, 0xbd, 0x63, 0x25, 0xe4, 0x07, 0xb4, 0x18, 0x62, 0x33, 0x97, 0xb3, 0x61, 0x37, 0x50,
	0xf8, 0xdd, 0x8e, 0x4c, 0xa8, 0xd2, 0x18, 0x2f, 0x8e, 0xbf, 0xc3, 0x55, 0xa3, 0xff, 0xb4, 0xff,
	0x1d, 0xfd, 0xa5, 0xa5, 0xe7, 0x69, 0xd9, 0x09, 0xed, 0x0e, 0xf2, 0x57, 0x3f, 0xba, 0x30, 0xd5,
	0xba, 0x49, 0x2c, 0xa4, 0xd9, 0xf0, 0x1a, 0x0a, 0x69, 0x68, 0x3c, 0x44, 0xc0, 0x31, 0xaa, 0xf8,
	0xe1, 0x52, 0x2e, 0xee, 0xe5, 0xe9, 0xf3, 0xb1, 0xc7, 0xf0, 0x35, 0xb6, 0xd3, 0x26, 0xa2, 0x35,
	0x9d, 0xa7, 0x71, 0x6f, 0x44, 0x50, 0xb4, 0xa7, 0x7b, 0x35, 0xa0, 0x88, 0xcb, 0xf5, 0xc6, 0x89,
	0xd3, 0x45, 0xdb, 0x22, 0x3e, 0x3c, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x33, 0x78, 0x1f, 0xdf,
	0x6a, 0x01, 0x00, 0x00,
}
